POST http://localhost:3002/api/notes 
Content-Type: application/json

{
    "content": "Esto es una prueba muy cutre 4",
    "important": true
}

###

POST http://localhost:3002/api/notes 
Content-Type: application/json

{
    "content": "Esto es una prueba muy cutre 5",
    "important": true
}